// const users = [
//   {
//     id: 1,
//     firstName: "Carla",
//     lastName: "Pulver",
//     email: "cpulver0@globo.com",
//     gender: "Female",
//     ip_address: "250.185.138.23",
//   },
//   {
//     id: 2,
//     firstName: "Prince",
//     lastName: "Camin",
//     email: "pcamin1@globo.com",
//     gender: "Male",
//     ip_address: "132.123.18.139",
//   },
//   {
//     id: 3,
//     firstName: "arcey",
//     lastName: "Tullis",
//     email: "dtullis2@t.co",
//     gender: "Female",
//     ip_address: "29.195.129.235",
//   },
//   {
//     id: 4,
//     firstName: "Petunia",
//     lastName: "MacMoyer",
//     email: "pmacmoyer3@comcast.net",
//     gender: "Female",
//     ip_address: "135.18.170.154",
//   },
//   {
//     id: 5,
//     firstName: "Ilysa",
//     lastName: "Terzo",
//     email: "iterzo4@theguardian.com",
//     gender: "Female",
//     ip_address: "245.145.237.70",
//   },
//   {
//     id: 6,
//     firstName: "Berkie",
//     lastName: "Bish",
//     email: "bbish5@dot.gov",
//     gender: "Genderqueer",
//     ip_address: "37.187.63.49",
//   },
//   {
//     id: 7,
//     firstName: "Tonnie",
//     lastName: "Saur",
//     email: "tsaur6@stanford.edu",
//     gender: "Male",
//     ip_address: "127.14.34.107",
//   },
//   {
//     id: 8,
//     firstName: "Laurice",
//     lastName: "Halfhide",
//     email: "lhalfhide7@stanford.edu",
//     gender: "Female",
//     ip_address: "47.231.85.108",
//   },
//   {
//     id: 9,
//     firstName: "Maximilien",
//     lastName: "Van der Hoven",
//     email: "mvanderhoven8@usnews.com",
//     gender: "Male",
//     ip_address: "180.152.206.222",
//   },
//   {
//     id: 10,
//     firstName: "Veda",
//     lastName: "Heading",
//     email: "vheading9@harvard.edu",
//     gender: "Female",
//     ip_address: "194.222.196.85",
//   },
//   {
//     id: 11,
//     firstName: "Em",
//     lastName: "Knobell",
//     email: "eknobella@arizona.edu",
//     gender: "Male",
//     ip_address: "63.156.138.231",
//   },
//   {
//     id: 12,
//     firstName: "Marylee",
//     lastName: "Bretherick",
//     email: "mbretherickb@blogger.com",
//     gender: "Female",
//     ip_address: "185.57.175.83",
//   },
//   {
//     id: 13,
//     firstName: "Livvy",
//     lastName: "Hercock",
//     email: "lhercockc@facebook.com",
//     gender: "Female",
//     ip_address: "140.202.114.163",
//   },
//   {
//     id: 14,
//     firstName: "Brant",
//     lastName: "Bartlett",
//     email: "bbartlettd@bigcartel.com",
//     gender: "Polygender",
//     ip_address: "231.130.57.203",
//   },
//   {
//     id: 15,
//     firstName: "Natale",
//     lastName: "Constable",
//     email: "nconstablee@wikipedia.org",
//     gender: "Male",
//     ip_address: "119.20.136.9",
//   },
//   {
//     id: 16,
//     firstName: "Matthias",
//     lastName: "Dawley",
//     email: "mdawleyf@time.com",
//     gender: "Male",
//     ip_address: "51.182.153.95",
//   },
//   {
//     id: 17,
//     firstName: "Abigale",
//     lastName: "Gleeson",
//     email: "agleesong@cdbaby.com",
//     gender: "Female",
//     ip_address: "237.245.248.64",
//   },
//   {
//     id: 18,
//     firstName: "Korry",
//     lastName: "Magog",
//     email: "kmagogh@bigcartel.com",
//     gender: "Female",
//     ip_address: "56.114.118.67",
//   },
//   {
//     id: 19,
//     firstName: "Britta",
//     lastName: "Postians",
//     email: "bpostiansi@nsw.gov.au",
//     gender: "Female",
//     ip_address: "187.221.138.25",
//   },
//   {
//     id: 20,
//     firstName: "Giusto",
//     lastName: "Blodgett",
//     email: "gblodgettj@samsung.com",
//     gender: "Genderqueer",
//     ip_address: "232.113.224.221",
//   },
//   {
//     id: 21,
//     firstName: "Susanne",
//     lastName: "MacFaul",
//     email: "smacfaulk@ed.gov",
//     gender: "Female",
//     ip_address: "28.192.37.38",
//   },
//   {
//     id: 22,
//     firstName: "Elaina",
//     lastName: "Carette",
//     email: "ecarettel@google.com.au",
//     gender: "Agender",
//     ip_address: "205.67.150.159",
//   },
//   {
//     id: 23,
//     firstName: "Gates",
//     lastName: "Deluca",
//     email: "gdelucam@yelp.com",
//     gender: "Female",
//     ip_address: "24.115.249.66",
//   },
//   {
//     id: 24,
//     firstName: "Hadlee",
//     lastName: "Panchin",
//     email: "hpanchinn@typepad.com",
//     gender: "Male",
//     ip_address: "164.70.118.32",
//   },
//   {
//     id: 25,
//     firstName: "Ingemar",
//     lastName: "Hawksley",
//     email: "ihawksleyo@gmpg.org",
//     gender: "Male",
//     ip_address: "127.26.4.103",
//   },
//   {
//     id: 26,
//     firstName: "Arty",
//     lastName: "Akess",
//     email: "aakessp@acquirethisname.com",
//     gender: "Male",
//     ip_address: "46.192.55.13",
//   },
//   {
//     id: 27,
//     firstName: "Laurence",
//     lastName: "Bartolini",
//     email: "lbartoliniq@etsy.com",
//     gender: "Male",
//     ip_address: "132.68.202.77",
//   },
//   {
//     id: 28,
//     firstName: "Emmeline",
//     lastName: "Laborda",
//     email: "elabordar@google.de",
//     gender: "Female",
//     ip_address: "76.208.47.228",
//   },
//   {
//     id: 29,
//     firstName: "Flor",
//     lastName: "Ciobutaru",
//     email: "fciobutarus@techcrunch.com",
//     gender: "Female",
//     ip_address: "147.74.199.193",
//   },
//   {
//     id: 30,
//     firstName: "Skipper",
//     lastName: "Gillbard",
//     email: "sgillbardt@timesonline.co.uk",
//     gender: "Male",
//     ip_address: "104.229.75.193",
//   },
//   {
//     id: 31,
//     firstName: "Melodee",
//     lastName: "Winkett",
//     email: "mwinkettu@barnesandnoble.com",
//     gender: "Female",
//     ip_address: "202.13.56.232",
//   },
//   {
//     id: 32,
//     firstName: "Hanny",
//     lastName: "Hullbrook",
//     email: "hhullbrookv@hud.gov",
//     gender: "Female",
//     ip_address: "229.23.215.141",
//   },
//   {
//     id: 33,
//     firstName: "Ellette",
//     lastName: "Wones",
//     email: "ewonesw@mysql.com",
//     gender: "Female",
//     ip_address: "197.98.245.253",
//   },
//   {
//     id: 34,
//     firstName: "Harmon",
//     lastName: "Tuxill",
//     email: "htuxillx@miibeian.gov.cn",
//     gender: "Male",
//     ip_address: "247.116.183.170",
//   },
//   {
//     id: 35,
//     firstName: "Corena",
//     lastName: "Smail",
//     email: "csmaily@youku.com",
//     gender: "Female",
//     ip_address: "80.169.191.131",
//   },
//   {
//     id: 36,
//     firstName: "Gan",
//     lastName: "Rapelli",
//     email: "grapelliz@studiopress.com",
//     gender: "Male",
//     ip_address: "29.139.116.194",
//   },
//   {
//     id: 37,
//     firstName: "Hinda",
//     lastName: "Nabarro",
//     email: "hnabarro10@skype.com",
//     gender: "Female",
//     ip_address: "221.71.244.222",
//   },
//   {
//     id: 38,
//     firstName: "Carrol",
//     lastName: "Chastagnier",
//     email: "cchastagnier11@who.int",
//     gender: "Male",
//     ip_address: "123.220.85.87",
//   },
//   {
//     id: 39,
//     firstName: "Kaycee",
//     lastName: "Flounders",
//     email: "kflounders12@sourceforge.net",
//     gender: "Female",
//     ip_address: "34.37.145.144",
//   },
//   {
//     id: 40,
//     firstName: "Kalindi",
//     lastName: "Milnthorpe",
//     email: "kmilnthorpe13@ycombinator.com",
//     gender: "Non-binary",
//     ip_address: "10.79.212.77",
//   },
//   {
//     id: 41,
//     firstName: "Max",
//     lastName: "Holligan",
//     email: "mholligan14@statcounter.com",
//     gender: "Female",
//     ip_address: "92.163.172.102",
//   },
//   {
//     id: 42,
//     firstName: "Hally",
//     lastName: "Guitton",
//     email: "hguitton15@prlog.org",
//     gender: "Female",
//     ip_address: "141.29.46.122",
//   },
//   {
//     id: 43,
//     firstName: "Philippa",
//     lastName: "McArley",
//     email: "pmcarley16@eepurl.com",
//     gender: "Female",
//     ip_address: "237.216.13.50",
//   },
//   {
//     id: 44,
//     firstName: "Marita",
//     lastName: "Pringer",
//     email: "mpringer17@freewebs.com",
//     gender: "Female",
//     ip_address: "78.21.20.20",
//   },
//   {
//     id: 45,
//     firstName: "Ermin",
//     lastName: "Innott",
//     email: "einnott18@yolasite.com",
//     gender: "Male",
//     ip_address: "41.250.147.153",
//   },
//   {
//     id: 46,
//     firstName: "Cordell",
//     lastName: "Barrow",
//     email: "cbarrow19@dion.ne.jp",
//     gender: "Male",
//     ip_address: "6.61.141.180",
//   },
//   {
//     id: 47,
//     firstName: "Thurston",
//     lastName: "Boor",
//     email: "tboor1a@cnn.com",
//     gender: "Male",
//     ip_address: "167.39.165.241",
//   },
//   {
//     id: 48,
//     firstName: "Gayle",
//     lastName: "Gundry",
//     email: "ggundry1b@friendfeed.com",
//     gender: "Male",
//     ip_address: "33.112.169.30",
//   },
//   {
//     id: 49,
//     firstName: "Nels",
//     lastName: "Spencelayh",
//     email: "nspencelayh1c@rambler.ru",
//     gender: "Male",
//     ip_address: "113.43.117.25",
//   },
//   {
//     id: 50,
//     firstName: "Crystie",
//     lastName: "Kohter",
//     email: "ckohter1d@patch.com",
//     gender: "Female",
//     ip_address: "199.137.208.14",
//   },
//   {
//     id: 51,
//     firstName: "Casar",
//     lastName: "Spanswick",
//     email: "cspanswick1e@deliciousdays.com",
//     gender: "Male",
//     ip_address: "119.92.176.140",
//   },
//   {
//     id: 52,
//     firstName: "Janis",
//     lastName: "Lerner",
//     email: "jlerner1f@over-blog.com",
//     gender: "Female",
//     ip_address: "229.160.41.140",
//   },
//   {
//     id: 53,
//     firstName: "Rodolphe",
//     lastName: "Vauter",
//     email: "rvauter1g@printfriendly.com",
//     gender: "Male",
//     ip_address: "162.162.108.114",
//   },
//   {
//     id: 54,
//     firstName: "Harmony",
//     lastName: "Maddicks",
//     email: "hmaddicks1h@nasa.gov",
//     gender: "Female",
//     ip_address: "22.93.52.49",
//   },
//   {
//     id: 55,
//     firstName: "Robert",
//     lastName: "Dowse",
//     email: "rdowse1i@microsoft.com",
//     gender: "Male",
//     ip_address: "77.220.233.38",
//   },
//   {
//     id: 56,
//     firstName: "Carri",
//     lastName: "Paybody",
//     email: "cpaybody1j@ted.com",
//     gender: "Female",
//     ip_address: "176.34.141.172",
//   },
//   {
//     id: 57,
//     firstName: "Didi",
//     lastName: "Thrower",
//     email: "dthrower1k@wiley.com",
//     gender: "Female",
//     ip_address: "34.188.21.139",
//   },
//   {
//     id: 58,
//     firstName: "Chick",
//     lastName: "Kynan",
//     email: "ckynan1l@opensource.org",
//     gender: "Bigender",
//     ip_address: "248.228.200.7",
//   },
//   {
//     id: 59,
//     firstName: "Boniface",
//     lastName: "Naden",
//     email: "bnaden1m@issuu.com",
//     gender: "Male",
//     ip_address: "34.74.44.85",
//   },
//   {
//     id: 60,
//     firstName: "Ursa",
//     lastName: "Coaten",
//     email: "ucoaten1n@msn.com",
//     gender: "Polygender",
//     ip_address: "244.219.1.124",
//   },
//   {
//     id: 61,
//     firstName: "Birgit",
//     lastName: "Resun",
//     email: "bresun1o@unesco.org",
//     gender: "Female",
//     ip_address: "75.129.15.62",
//   },
//   {
//     id: 62,
//     firstName: "Merrill",
//     lastName: "Chatelot",
//     email: "mchatelot1p@moonfruit.com",
//     gender: "Female",
//     ip_address: "249.62.71.34",
//   },
//   {
//     id: 63,
//     firstName: "Suki",
//     lastName: "Dawidowicz",
//     email: "sdawidowicz1q@home.pl",
//     gender: "Non-binary",
//     ip_address: "100.59.21.189",
//   },
//   {
//     id: 64,
//     firstName: "Sibeal",
//     lastName: "Marwick",
//     email: "smarwick1r@joomla.org",
//     gender: "Female",
//     ip_address: "189.97.111.10",
//   },
//   {
//     id: 65,
//     firstName: "Lyndsay",
//     lastName: "Lysaght",
//     email: "llysaght1s@ebay.co.uk",
//     gender: "Female",
//     ip_address: "91.197.0.246",
//   },
//   {
//     id: 3,
//     firstName: "arcey",
//     lastName: "Bullis",
//     email: "dtullis2@t.co",
//     gender: "Female",
//     ip_address: "29.195.129.235",
//   },
//   {
//     id: 66,
//     firstName: "Cob",
//     lastName: "Bynold",
//     email: "cbynold1t@opensource.org",
//     gender: "Male",
//     ip_address: "137.112.201.191",
//   },
//   {
//     id: 67,
//     firstName: "Sherri",
//     lastName: "Baroc",
//     email: "sbaroc1u@163.com",
//     gender: "Female",
//     ip_address: "13.50.4.13",
//   },
//   {
//     id: 68,
//     firstName: "Wilhelmina",
//     lastName: "Caven",
//     email: "wcaven1v@multiply.com",
//     gender: "Female",
//     ip_address: "9.141.222.201",
//   },
//   {
//     id: 69,
//     firstName: "Larissa",
//     lastName: "Wais",
//     email: "lwais1w@vistaprint.com",
//     gender: "Female",
//     ip_address: "228.51.71.192",
//   },
//   {
//     id: 70,
//     firstName: "Aleda",
//     lastName: "Jeste",
//     email: "ajeste1x@bbc.co.uk",
//     gender: "Female",
//     ip_address: "164.145.8.216",
//   },
//   {
//     id: 71,
//     firstName: "Gilli",
//     lastName: "Klebes",
//     email: "gklebes1y@google.nl",
//     gender: "Female",
//     ip_address: "52.194.61.154",
//   },
//   {
//     id: 72,
//     firstName: "Drugi",
//     lastName: "Bloxholm",
//     email: "dbloxholm1z@google.fr",
//     gender: "Non-binary",
//     ip_address: "242.42.142.189",
//   },
//   {
//     id: 73,
//     firstName: "Tamiko",
//     lastName: "Couvet",
//     email: "tcouvet20@macromedia.com",
//     gender: "Female",
//     ip_address: "215.238.155.233",
//   },
//   {
//     id: 74,
//     firstName: "Adeline",
//     lastName: "Cosh",
//     email: "acosh21@slideshare.net",
//     gender: "Female",
//     ip_address: "243.154.125.140",
//   },
//   {
//     id: 75,
//     firstName: "Vi",
//     lastName: "Gallehock",
//     email: "vgallehock22@omniture.com",
//     gender: "Female",
//     ip_address: "237.26.37.39",
//   },
//   {
//     id: 76,
//     firstName: "Madelene",
//     lastName: "Maulin",
//     email: "mmaulin23@unblog.fr",
//     gender: "Female",
//     ip_address: "151.62.191.212",
//   },
//   {
//     id: 77,
//     firstName: "Eva",
//     lastName: "McAmish",
//     email: "emcamish24@gizmodo.com",
//     gender: "Female",
//     ip_address: "16.196.72.248",
//   },
//   {
//     id: 78,
//     firstName: "Brennan",
//     lastName: "Antonat",
//     email: "bantonat25@yolasite.com",
//     gender: "Male",
//     ip_address: "251.224.42.246",
//   },
//   {
//     id: 79,
//     firstName: "Kalila",
//     lastName: "Le Houx",
//     email: "klehoux26@columbia.edu",
//     gender: "Female",
//     ip_address: "190.192.215.222",
//   },
//   {
//     id: 80,
//     firstName: "Benedick",
//     lastName: "Haszard",
//     email: "bhaszard27@msu.edu",
//     gender: "Male",
//     ip_address: "80.223.252.214",
//   },
//   {
//     id: 81,
//     firstName: "Briney",
//     lastName: "Rainard",
//     email: "brainard28@dot.gov",
//     gender: "Female",
//     ip_address: "160.84.220.74",
//   },
//   {
//     id: 82,
//     firstName: "Sven",
//     lastName: "MacAlpine",
//     email: "smacalpine29@nbcnews.com",
//     gender: "Male",
//     ip_address: "82.68.233.120",
//   },
//   {
//     id: 83,
//     firstName: "Yankee",
//     lastName: "Cars",
//     email: "ycars2a@washington.edu",
//     gender: "Male",
//     ip_address: "42.19.165.168",
//   },
//   {
//     id: 84,
//     firstName: "Erny",
//     lastName: "Adshead",
//     email: "eadshead2b@dailymotion.com",
//     gender: "Male",
//     ip_address: "212.184.180.220",
//   },
//   {
//     id: 85,
//     firstName: "Erie",
//     lastName: "Knoles",
//     email: "eknoles2c@yahoo.co.jp",
//     gender: "Male",
//     ip_address: "241.210.25.98",
//   },
//   {
//     id: 86,
//     firstName: "Loni",
//     lastName: "McNeachtain",
//     email: "lmcneachtain2d@lycos.com",
//     gender: "Female",
//     ip_address: "232.14.172.100",
//   },
//   {
//     id: 87,
//     firstName: "Granger",
//     lastName: "Planque",
//     email: "gplanque2e@comcast.net",
//     gender: "Agender",
//     ip_address: "111.81.206.126",
//   },
//   {
//     id: 88,
//     firstName: "Tisha",
//     lastName: "Krienke",
//     email: "tkrienke2f@arizona.edu",
//     gender: "Female",
//     ip_address: "191.136.214.106",
//   },
//   {
//     id: 89,
//     firstName: "Meghann",
//     lastName: "Rush",
//     email: "mrush2g@nyu.edu",
//     gender: "Female",
//     ip_address: "199.88.129.255",
//   },
//   {
//     id: 90,
//     firstName: "Fernandina",
//     lastName: "Doughartie",
//     email: "fdoughartie2h@google.es",
//     gender: "Bigender",
//     ip_address: "228.218.92.38",
//   },
//   {
//     id: 91,
//     firstName: "Elton",
//     lastName: "Iaduccelli",
//     email: "eiaduccelli2i@networksolutions.com",
//     gender: "Male",
//     ip_address: "112.219.190.150",
//   },
//   {
//     id: 92,
//     firstName: "Malinde",
//     lastName: "Roskelly",
//     email: "mroskelly2j@vimeo.com",
//     gender: "Female",
//     ip_address: "128.17.39.22",
//   },
//   {
//     id: 93,
//     firstName: "Arlana",
//     lastName: "Brumble",
//     email: "abrumble2k@guardian.co.uk",
//     gender: "Female",
//     ip_address: "130.69.67.16",
//   },
//   {
//     id: 94,
//     firstName: "Tammy",
//     lastName: "Warricker",
//     email: "twarricker2l@mashable.com",
//     gender: "Male",
//     ip_address: "161.4.118.164",
//   },
//   {
//     id: 95,
//     firstName: "Odessa",
//     lastName: "Kelberman",
//     email: "okelberman2m@samsung.com",
//     gender: "Female",
//     ip_address: "21.217.110.107",
//   },
//   {
//     id: 96,
//     firstName: "Lalo",
//     lastName: "Goforth",
//     email: "lgoforth2n@usatoday.com",
//     gender: "Male",
//     ip_address: "177.115.222.136",
//   },
//   {
//     id: 97,
//     firstName: "Chrystal",
//     lastName: "Halwood",
//     email: "chalwood2o@g.co",
//     gender: "Female",
//     ip_address: "58.245.210.226",
//   },
//   {
//     id: 98,
//     firstName: "Genna",
//     lastName: "Barham",
//     email: "gbarham2p@kickstarter.com",
//     gender: "Female",
//     ip_address: "73.114.49.143",
//   },
//   {
//     id: 99,
//     firstName: "Justinian",
//     lastName: "Minchella",
//     email: "jminchella2q@feedburner.com",
//     gender: "Male",
//     ip_address: "68.172.236.141",
//   },
//   {
//     id: 100,
//     firstName: "Joella",
//     lastName: "Gibby",
//     email: "jgibby2r@dmoz.org",
//     gender: "Female",
//     ip_address: "196.188.30.208",
//   },
// ];
// // 1. Пошук юзера
// // 2. Сортування за ім'ям
// // 3. Сортування за прізвищем

// // const findUser = (array, searchQuery) => {
// //   if (!searchQuery || searchQuery.length <= 3) {
// //     return "Error input";
// //   }
// //   return array.find(({ firstName, lastName }) =>
// //     `${firstName} ${lastName}`
// //       .toLocaleLowerCase()
// //       .includes(searchQuery.toLocaleLowerCase())
// //   );
// // };

// // // console.log(findUser(users, "eLai66787"));

// // const filterUserByName = (array, searchQuery) => {
// //   if (!searchQuery || searchQuery.length < 3) {
// //     return "Error input";
// //   }
// //   return array.filter(({ firstName, lastName }) =>
// //     `${firstName} ${lastName}`
// //       .toLocaleLowerCase()
// //       .includes(searchQuery.toLocaleLowerCase())
// //   );
// // };
// // // console.log(filterUserByName(users, "eLa234"));

// // const sortFromName = (array) => {
// //   return [...array].sort((a, b) =>
// //     `${a.firstName}${a.lastName}`.localeCompare(`${b.firstName}${b.lastName}`)
// //   );
// // };

// // console.log(sortFromName(users));

// const getEmailDomains = (array) => {
//   return array.reduce((acc, { email }) => {
//     const [, domain] = email.split("@");
//     return acc.includes(domain) ? acc : acc + domain + `\n`;

//     //
//     // console.log(domain);
//     // const index = email.indexOf("@");
//     // const domain1 = email.slice(index);
//     // console.log(domain1);
//     //   Dont work!!!Error junior!
//     // const [a, b, ...c] = email;
//     // console.log(a, b, c);
//   }, "");
// };
// console.log(getEmailDomains(users));

// потрібно створити метод(ф-ю) яка буде виводити ім'я і вік, і який можна використати для обох об'єктів

const user1 = {
  name: "Den",
  age: 24,
  getNameAndAge() {
    console.log(` Your name ${this.name} and your age ${this.age}`);
  },
};

const user2 = {
  name: "Cergii",
  age: 30,
  email: "den@example.com",
};
const copy = user1.getNameAndAge;
user1.getNameAndAge();
copy();
user2.getNameAndAge = copy;
user2.getNameAndAge();
